### ISSUE TITLE
Issue Observed in IRCODEC modules

### ISSUE THREAD

**Issue by gecb1609** [kentwait/ircodec#2]
Dear Kent.

Hope you are doing well.

I was trying your code located in https://pypi.org/project/ircodec/#modal-close.
I tried to execute the exactly the same code in my Raspberry Pi 3 version. However I am always getting the below error:

Type Error : _init_() missing one required positional argument : 'name' in the below line 

controller = CommandSet(emitter_gpio=22, receiver_gpio=23, description='TV remote')

When name is assigned as the key name, the codes runs, key codes are sent, however TV is unable to respond.
I am not sure whether the system has recorded the key codes correctly.

Could you please help me in recovering the above error ? am I missing something?
Kindly support on this.

**Comment by gecb1609** [comment]
I am using debian bullseye/raspbian bulls eye as OS.

**Comment by nini1294** [comment]
Hi, I had the same issue, I was able to get it to work by modifying the line like below
`controller = CommandSet(emitter_gpio=22, receiver_gpio=23, name='TV', description='TV remote')`

I just added a parameter called "name"

**Comment by kentwait** [comment]
You're right. `name` is required but the README doesn't say so. I updated the README to reflect this.
