### ISSUE TITLE
Error that message is too short! 

### ISSUE THREAD

**Issue by Prototipe397** [kentwait/ircodec#3]
When I try to send and receive IR signal by ircodec from mitsubishi AC I end with error that "message is to short!" Anybody can help me?

**Comment by kentwait** [comment]
Air conditioner remotes are tricky. It sends out the whole state (temp, mode, swing mode, etc) every time you change even just a single setting on the remote. Sometimes ircodec works and sometimes (more) it doesn't. 
I suggest you try a more sophisticated solution (ie. LIRC on Linux) or use the PIGPIO library directly without ircodec.

ircodec is piggy-backing on the PIGPIO presets so apologies I couldn't help you more.

Here's some links for others who will stumble on this.
- https://blog.depau.eu/2021/06/12/ir-remote-reveng/
- https://forum.arduino.cc/t/decoding-the-raw-ir-signal-of-an-ac/1262089
- https://www.vishay.com/docs/80071/dataform.pdf
